---
components:
  - name: max1704x
    description: Driver for MAX17043/MAX17044/MAX17048/MAX17049 battery fuel gauge
    group: battery
    groups: []
    code_owners: shuki25
    depends:
      - name: i2cdev
      - name: log
      - name: esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp8266
      - name: esp32s2
      - name: esp32c3
    licenses:
      - name: BSD-3
    copyrights:
      - author:
          name: shuki25
        year: 2022
